name: Pull Request Demo

on:
  push:
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        
    - name: Build
      run: |
        npm ci
        npm run build-prod-min
        npm run build-css


    - name: Find Pull Request number
      uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        state: open

    - run: echo "Your PR is ${PR}"
      if: success() && steps.findPr.outputs.number
      env:
        PR: ${{ steps.findPr.outputs.pr }}

    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@4.1.0
    #   with:
    #     branch: gh-pages
    #     folder: dist
    #     target-folder: ${{ steps.findPr.outputs.pr }}