name: Pull Request Demo

on:
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - run: |
        npm ci
        npm run build-prod-min
        npm run build-css

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: dist
        target-folder: oliver
